"""changed DBActivity.df column to df_json

Revision ID: 1382008cc690
Revises: 9d5505756cd6
Create Date: 2021-07-15 18:38:29.281656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1382008cc690'
down_revision = '9d5505756cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.drop_column('df')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('df', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
