"""renamed df_json to dataframe in db_activity

Revision ID: 7bd207bdf95a
Revises: db728e1b5953
Create Date: 2021-08-24 10:32:07.037332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bd207bdf95a'
down_revision = 'db728e1b5953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataframe', sa.JSON(), nullable=True))
        batch_op.drop_column('df_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('df_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('dataframe')

    # ### end Alembic commands ###
