"""initial

Revision ID: 9d5505756cd6
Revises: 
Create Date: 2021-07-14 13:02:16.595297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5505756cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('strava_id', sa.Integer(), nullable=True),
    sa.Column('strava_scope', sa.Text(), nullable=True),
    sa.Column('strava_access_token', sa.String(length=40), nullable=True),
    sa.Column('strava_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('strava_refresh_token', sa.String(length=40), nullable=True),
    sa.Column('strava_athlete_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('strava_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('db_activity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('laps', sa.JSON(), nullable=True),
    sa.Column('streams', sa.JSON(), nullable=True),
    sa.Column('df', sa.JSON(), nullable=True),
    sa.Column('intervals', sa.JSON(), nullable=True),
    sa.Column('blob', sa.BLOB(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.strava_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_activity')
    op.drop_table('user')
    # ### end Alembic commands ###
