"""Changed activity_id field to BigInt in db_activity + removed comment field

Revision ID: f1974e808b77
Revises: e7d5976981bb
Create Date: 2021-08-19 16:55:30.694652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1974e808b77'
down_revision = 'e7d5976981bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.drop_column('comment')

        op.alter_column('db_activity', 'activity_id', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))

        op.alter_column('db_activity', 'activity_id', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
